kind: List
metadata: {}
apiVersion: v1
items:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      generation: 2
      labels:
        app: busybox
      name: busybox
    spec:
      lookupPolicy:
        local: false
      tags:
      - annotations:
          openshift.io/imported-from: busybox
        from:
          kind: DockerImage
          name: busybox
        generation: 2
        importPolicy: {}
        name: latest
        referencePolicy:
          type: Source
    status:
      dockerImageRepository: ""
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      creationTimestamp: null
      generation: 2
      labels:
        app: busybox
      name: busybox
    spec:
      replicas: 1
      selector:
        app: busybox
        deploymentconfig: busybox
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: busybox
            deploymentconfig: busybox
        spec:
          containers:
          - args:
            - "99999999"
            command:
            - sleep
            image: busybox:latest
            imagePullPolicy: IfNotPresent
            name: busybox
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
      - type: ConfigChange
